export const FETCH_BLOGS_REQUEST = "FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE";

export const CREATE_BLOG = "CREATE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";

export const FAVORITE_BLOGS_REQUEST = "FAVORITE_BLOGS_REQUEST";
export const FAVORITE_BLOGS_SUCCESS = "FAVORITE_BLOGS_SUCCESS";
export const FAVORITE_BLOGS_FAILURE = "FAVORITE_BLOGS_FAILURE";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
//
export const REPLY_REQUEST = "REPLY_REQUEST";
//
export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
//
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
